version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.0-latest
    environment:
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-db

  zabbix-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:6.0-latest
    environment:
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
      - zabbix-db
